=== api-evangelist/reclaim-ai/json-schema/reclaim-ai-credential.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://api.app.reclaim.ai/schemas/Credential",
  "title": "Credential",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "userId": {
      "type": "string"
    },
    "provider": {
      "type": "string"
    },
    "principal": {
      "type": "string"
    },
    "name": {
      "$ref": "#/components/schemas/CredentialName"
    },
    "splitScopes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "scopes": {
      "type": "string"
    },
    "data": {},
    "avatar": {
      "type": "string"
    },
    "userInfo": {
      "$ref": "#/components/schemas/GoogleUserInfo"
    },
    "updated": {
      "type": "string",
      "format": "date-time"
    },
    "key": {
      "type": "string"
    },
    "valid": {
      "type": "boolean"
    },
    "validMicrosoftCredential": {
      "type": "boolean"
    },
    "serviceAccount": {
      "type": "boolean"
    },
    "connectedAccountType": {
      "$ref": "#/components/schemas/ConnectedAccountType"
    },
    "email": {
      "type": "string"
    },
    "credentialType": {
      "$ref": "#/components/schemas/CredentialType"
    },
    "googleWorkspaceCredential": {
      "type": "boolean"
    },
    "googleNonWorkspaceCredential": {
      "type": "boolean"
    },
    "microsoftWorkspaceCredential": {
      "type": "boolean"
    },
    "microsoftNonWorkspaceCredential": {
      "type": "boolean"
    }
  }
}

=== api-evangelist/reclaim-ai/examples/reclaim-ai-credential-example.json
{
  "id": 1,
  "userId": "string",
  "provider": "string",
  "principal": "string",
  "name": {
    "email": "string"
  },
  "splitScopes": [
    "string"
  ],
  "scopes": "string",
  "avatar": "string",
  "userInfo": {
    "sub": "string",
    "email": "string",
    "email_verified": false,
    "name": "string",
    "given_name": "string",
    "family_name": "string",
    "picture": "string",
    "locale": "string",
    "hd": "string",
    "oid": "string"
  }
}
